# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDiscipline', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSessions',
            fields=[
                ('idTrainingSessions', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('idDiscipline', models.IntegerField()),
                ('idGroup', models.IntegerField()),
                ('idClassroom', models.IntegerField()),
                ('idTeacher', models.IntegerField()),
                ('datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='idGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.TrainingSessions'),
        ),
    ]
