# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='id',
        ),
        migrations.AddField(
            model_name='groups',
            name='idTrainingSessions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.TrainingSessions'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='idGroup',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
