# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-22 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_editor', '0002_auto_20171016_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('idGroup', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=50)),
                ('build', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('idDiscipline', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('idEvent', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('begin', models.DateTimeField(verbose_name='begin')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('idClassroom', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.Classrooms')),
                ('idDiscipline', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.Disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDiscipline',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('discipline', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.Disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('discipline', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.Disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('idGroup', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='groups',
            name='idDiscipline',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='idTrainingSessions',
        ),
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='TrainingSessions',
        ),
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.Groups'),
        ),
        migrations.AddField(
            model_name='studentdiscipline',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.Students'),
        ),
        migrations.AddField(
            model_name='groupdiscipline',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.Groups'),
        ),
        migrations.AddField(
            model_name='events',
            name='idTeacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schedule_editor.Teachers'),
        ),
    ]
